baseURL = "https://tvoje-adresa.netlify.app/"
title = "Jungle Protocol"
theme = "blowfish"
defaultContentLanguage = "en"

[configDir]
  default = "config"

[taxonomies]
  category = "categories"
  tag = "tags"
  zeme = "země"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
